-- =====================================================================
-- BASELINE SCHEMA — snapshot del esquema public del proyecto en vivo.
-- Generado para versionar el esquema (antes solo existía un .sql suelto).
-- Captura: tablas, constraints (PK/FK/UNIQUE), índices, triggers y funciones RPC.
--
-- Nota: para un restore exacto clean-room usar `supabase db dump --schema public`
-- o `pg_dump --schema-only`. Este archivo es una reconstrucción de referencia.
-- RLS: habilitado en todas las tablas (ver 2026_06_security_hardening.sql).
-- =====================================================================

-- ---------------------------------------------------------------------
-- TABLAS
-- ---------------------------------------------------------------------

create table if not exists public.empresas (
  id          bigint generated by default as identity,
  nombre      text not null,
  created_by  uuid not null,
  creado_en   timestamptz not null default now()
);

create table if not exists public.empresa_miembros (
  id            bigint generated by default as identity,
  empresa_id    bigint not null,
  user_id       uuid not null,
  rol           text not null default 'cajero',
  invitado_por  uuid,
  creado_en     timestamptz not null default now()
);

create table if not exists public.invitaciones (
  id            bigint generated by default as identity,
  empresa_id    bigint not null,
  email         text not null,
  rol           text not null default 'cajero',
  token         uuid not null default gen_random_uuid(),
  estado        text not null default 'pendiente',
  invitado_por  uuid not null,
  creado_en     timestamptz not null default now(),
  expira_en     timestamptz not null default (now() + interval '7 days')
);

create table if not exists public.cuentas_receptoras (
  id          bigint generated by default as identity,
  nombre      text not null,
  banco       text not null,
  telefono    text not null,
  cedula      text not null,
  activa      boolean not null default true,
  creado_en   timestamptz not null default now(),
  empresa_id  bigint
);

create table if not exists public.pagos (
  id                   bigint generated by default as identity,
  monto                numeric not null,
  banco                text not null,
  cedula               text not null,
  telefono             text,
  fecha                date not null,
  hora                 text,
  referencia           text not null,
  concepto             text,
  cuenta_receptora_id  bigint,
  imagen_uri           text,
  creado_en            timestamptz not null default now(),
  actualizado_en       timestamptz not null default now(),
  estado               text not null default 'confirmado',
  origen               text not null default 'manual',
  campos_corregidos    text[],
  empresa_id           bigint
);

create table if not exists public.scan_logs (
  id                 bigint generated by default as identity,
  pago_id            bigint,
  imagen_uri         text,
  scan_started_at    timestamptz not null default now(),
  scan_completed_at  timestamptz,
  scan_status        text not null default 'processing',
  campos_extraidos   jsonb,
  campos_finales     jsonb,
  creado_en          timestamptz not null default now(),
  empresa_id         bigint
);

create table if not exists public.metas_mensuales (
  id             bigint generated by default as identity,
  mes            text not null,
  meta_ingresos  numeric not null,
  creado_en      timestamptz not null default now(),
  empresa_id     bigint
);

create table if not exists public.audit_log (
  id           bigint generated by default as identity,
  tabla        text not null,
  registro_id  bigint not null,
  accion       text not null,
  cambios      jsonb,
  creado_en    timestamptz not null default now(),
  empresa_id   bigint
);

create table if not exists public.bcv_rates (
  fecha       date not null,
  promedio    numeric not null,
  fetched_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- CONSTRAINTS (PK / UNIQUE / FK)
-- ---------------------------------------------------------------------
ALTER TABLE public.empresas ADD CONSTRAINT empresas_pkey PRIMARY KEY (id);
ALTER TABLE public.empresas ADD CONSTRAINT empresas_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.empresa_miembros ADD CONSTRAINT empresa_miembros_pkey PRIMARY KEY (id);
ALTER TABLE public.empresa_miembros ADD CONSTRAINT empresa_miembros_empresa_id_user_id_key UNIQUE (empresa_id, user_id);
ALTER TABLE public.empresa_miembros ADD CONSTRAINT empresa_miembros_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public.empresa_miembros ADD CONSTRAINT empresa_miembros_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.empresa_miembros ADD CONSTRAINT empresa_miembros_invitado_por_fkey FOREIGN KEY (invitado_por) REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.invitaciones ADD CONSTRAINT invitaciones_pkey PRIMARY KEY (id);
ALTER TABLE public.invitaciones ADD CONSTRAINT invitaciones_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public.invitaciones ADD CONSTRAINT invitaciones_invitado_por_fkey FOREIGN KEY (invitado_por) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.cuentas_receptoras ADD CONSTRAINT cuentas_receptoras_pkey PRIMARY KEY (id);
ALTER TABLE public.cuentas_receptoras ADD CONSTRAINT cuentas_receptoras_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;

ALTER TABLE public.pagos ADD CONSTRAINT pagos_pkey PRIMARY KEY (id);
ALTER TABLE public.pagos ADD CONSTRAINT pagos_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public.pagos ADD CONSTRAINT pagos_cuenta_receptora_id_fkey FOREIGN KEY (cuenta_receptora_id) REFERENCES cuentas_receptoras(id) ON DELETE SET NULL;

ALTER TABLE public.scan_logs ADD CONSTRAINT scan_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.scan_logs ADD CONSTRAINT scan_logs_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE public.scan_logs ADD CONSTRAINT scan_logs_pago_id_fkey FOREIGN KEY (pago_id) REFERENCES pagos(id) ON DELETE SET NULL;

ALTER TABLE public.metas_mensuales ADD CONSTRAINT metas_mensuales_pkey PRIMARY KEY (id);
ALTER TABLE public.metas_mensuales ADD CONSTRAINT metas_mensuales_mes_key UNIQUE (mes);
ALTER TABLE public.metas_mensuales ADD CONSTRAINT metas_mensuales_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;

ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;

ALTER TABLE public.bcv_rates ADD CONSTRAINT bcv_rates_pkey PRIMARY KEY (fecha);

-- ---------------------------------------------------------------------
-- ÍNDICES (no incluye los implícitos de PK/UNIQUE de arriba)
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS audit_log_empresa_id_idx ON public.audit_log USING btree (empresa_id);
CREATE INDEX IF NOT EXISTS bcv_rates_fecha_idx ON public.bcv_rates USING btree (fecha DESC);
CREATE INDEX IF NOT EXISTS cuentas_empresa_idx ON public.cuentas_receptoras USING btree (empresa_id);
CREATE INDEX IF NOT EXISTS empresa_miembros_empresa_idx ON public.empresa_miembros USING btree (empresa_id);
CREATE INDEX IF NOT EXISTS empresa_miembros_invitado_por_idx ON public.empresa_miembros USING btree (invitado_por);
CREATE INDEX IF NOT EXISTS empresa_miembros_user_idx ON public.empresa_miembros USING btree (user_id);
CREATE INDEX IF NOT EXISTS empresas_created_by_idx ON public.empresas USING btree (created_by);
CREATE INDEX IF NOT EXISTS invitaciones_empresa_id_idx ON public.invitaciones USING btree (empresa_id);
CREATE INDEX IF NOT EXISTS invitaciones_invitado_por_idx ON public.invitaciones USING btree (invitado_por);
CREATE INDEX IF NOT EXISTS metas_mensuales_empresa_id_idx ON public.metas_mensuales USING btree (empresa_id);
CREATE INDEX IF NOT EXISTS pagos_cuenta_receptora_id_idx ON public.pagos USING btree (cuenta_receptora_id);
CREATE INDEX IF NOT EXISTS pagos_empresa_idx ON public.pagos USING btree (empresa_id);
CREATE INDEX IF NOT EXISTS pagos_estado_idx ON public.pagos USING btree (estado);
CREATE INDEX IF NOT EXISTS pagos_fecha_idx ON public.pagos USING btree (fecha);
CREATE INDEX IF NOT EXISTS pagos_referencia_idx ON public.pagos USING btree (referencia);
CREATE INDEX IF NOT EXISTS idx_scan_logs_empresa_started ON public.scan_logs USING btree (empresa_id, scan_started_at DESC);
CREATE INDEX IF NOT EXISTS scan_logs_empresa_id_idx ON public.scan_logs USING btree (empresa_id);
CREATE INDEX IF NOT EXISTS scan_logs_pago_id_idx ON public.scan_logs USING btree (pago_id);

-- ---------------------------------------------------------------------
-- TRIGGERS
-- ---------------------------------------------------------------------
CREATE TRIGGER trg_pagos_set_actualizado_en BEFORE UPDATE ON public.pagos
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

-- ---------------------------------------------------------------------
-- FUNCIONES (RPC usadas por el backend)
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_actualizado_en()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $function$
BEGIN
  NEW.actualizado_en := now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_pagos_duplicados(p_empresa_id bigint)
 RETURNS SETOF pagos LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$
  SELECT p.*
  FROM pagos p
  JOIN (
    SELECT banco, referencia
    FROM pagos
    WHERE empresa_id = p_empresa_id
    GROUP BY banco, referencia
    HAVING COUNT(*) > 1
  ) g ON p.banco = g.banco AND p.referencia = g.referencia
  WHERE p.empresa_id = p_empresa_id
  ORDER BY p.banco, p.referencia, p.fecha DESC, p.id DESC;
$function$;

CREATE OR REPLACE FUNCTION public.get_pagos_editados_ids(p_empresa_id bigint)
 RETURNS SETOF bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$
  SELECT id FROM pagos
  WHERE empresa_id = p_empresa_id
    AND actualizado_en > creado_en + interval '1 second';
$function$;

CREATE OR REPLACE FUNCTION public.get_scan_stats(p_empresa_id bigint)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  result jsonb; v_total bigint; v_failed bigint; v_avg_ms numeric; v_corrected bigint;
BEGIN
  SELECT COUNT(*) INTO v_total FROM scan_logs WHERE empresa_id = p_empresa_id;
  IF v_total = 0 THEN
    RETURN jsonb_build_object('tasa_rechazo', 0, 'tiempo_promedio_ms', 0, 'tasa_correccion', 0, 'total_scans', 0);
  END IF;
  SELECT COUNT(*) INTO v_failed FROM scan_logs WHERE scan_status LIKE 'failed_%' AND empresa_id = p_empresa_id;
  SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (scan_completed_at - scan_started_at)) * 1000), 0)
    INTO v_avg_ms FROM scan_logs WHERE scan_completed_at IS NOT NULL AND empresa_id = p_empresa_id;
  SELECT COUNT(*) INTO v_corrected FROM scan_logs
    WHERE campos_extraidos IS NOT NULL AND campos_finales IS NOT NULL
      AND campos_extraidos IS DISTINCT FROM campos_finales AND empresa_id = p_empresa_id;
  SELECT jsonb_build_object(
    'tasa_rechazo', ROUND((v_failed::numeric / v_total) * 100, 1),
    'tiempo_promedio_ms', ROUND(v_avg_ms),
    'tasa_correccion', ROUND((v_corrected::numeric / GREATEST(v_total - v_failed, 1)) * 100, 1),
    'total_scans', v_total
  ) INTO result;
  RETURN result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_stats_breakdown(p_desde text, p_hasta text, p_group_by text, p_empresa_id bigint)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE result jsonb;
BEGIN
  IF p_group_by = 'banco' THEN
    SELECT COALESCE(jsonb_agg(row_to_json(r)), '[]'::jsonb) INTO result FROM (
      SELECT banco AS grupo, SUM(monto)::numeric AS total, COUNT(*)::int AS cantidad
      FROM pagos WHERE fecha >= p_desde::date AND fecha <= p_hasta::date AND estado = 'confirmado' AND empresa_id = p_empresa_id
      GROUP BY banco ORDER BY total DESC) r;
  ELSIF p_group_by = 'dia' THEN
    SELECT COALESCE(jsonb_agg(row_to_json(r)), '[]'::jsonb) INTO result FROM (
      SELECT fecha::text AS grupo, SUM(monto)::numeric AS total, COUNT(*)::int AS cantidad
      FROM pagos WHERE fecha >= p_desde::date AND fecha <= p_hasta::date AND estado = 'confirmado' AND empresa_id = p_empresa_id
      GROUP BY fecha ORDER BY fecha ASC) r;
  ELSIF p_group_by = 'hora' THEN
    SELECT COALESCE(jsonb_agg(row_to_json(r)), '[]'::jsonb) INTO result FROM (
      SELECT COALESCE(LEFT(hora, 2), 'N/A') AS grupo, SUM(monto)::numeric AS total, COUNT(*)::int AS cantidad
      FROM pagos WHERE fecha >= p_desde::date AND fecha <= p_hasta::date AND estado = 'confirmado' AND empresa_id = p_empresa_id
      GROUP BY COALESCE(LEFT(hora, 2), 'N/A') ORDER BY grupo ASC) r;
  ELSE
    result := '[]'::jsonb;
  END IF;
  RETURN result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_stats_extra(p_empresa_id bigint)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
declare
  result jsonb;
  v_prev_month_start date := (date_trunc('month', current_date) - interval '1 month')::date;
  v_prev_month_end   date := (date_trunc('month', current_date) - interval '1 day')::date;
begin
  select jsonb_build_object(
    'total_mes_anterior', coalesce((
      select sum(monto) from pagos
      where empresa_id = p_empresa_id and estado = 'confirmado'
        and fecha >= v_prev_month_start and fecha <= v_prev_month_end), 0),
    'cantidad_mes_anterior', (
      select count(*) from pagos
      where empresa_id = p_empresa_id and estado = 'confirmado'
        and fecha >= v_prev_month_start and fecha <= v_prev_month_end),
    'ticket_promedio_historico', coalesce((
      select avg(monto) from pagos
      where empresa_id = p_empresa_id and estado = 'confirmado'), 0)
  ) into result;
  return result;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_stats_monthly(p_empresa_id bigint)
 RETURNS TABLE(mes text, total numeric, cantidad bigint) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$
  with meses as (
    select generate_series(
      date_trunc('month', current_date) - interval '11 months',
      date_trunc('month', current_date),
      interval '1 month')::date as inicio)
  select to_char(m.inicio, 'YYYY-MM') as mes,
    coalesce(sum(p.monto), 0)::numeric as total,
    count(p.id)::bigint as cantidad
  from meses m
  left join public.pagos p
    on p.empresa_id = p_empresa_id and p.estado = 'confirmado'
   and p.fecha >= m.inicio and p.fecha < (m.inicio + interval '1 month')::date
  group by m.inicio order by m.inicio;
$function$;

CREATE OR REPLACE FUNCTION public.get_stats_summary(p_empresa_id bigint)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  result jsonb;
  v_today date := CURRENT_DATE;
  v_yesterday date := CURRENT_DATE - 1;
  v_week_start date := date_trunc('week', CURRENT_DATE)::date;
  v_prev_week_start date := (date_trunc('week', CURRENT_DATE) - interval '7 days')::date;
  v_prev_week_end date := (date_trunc('week', CURRENT_DATE) - interval '1 day')::date;
  v_month_start date := date_trunc('month', CURRENT_DATE)::date;
  v_month_end date := (date_trunc('month', CURRENT_DATE) + interval '1 month' - interval '1 day')::date;
  v_mes_actual text := to_char(CURRENT_DATE, 'YYYY-MM');
BEGIN
  SELECT jsonb_build_object(
    'total_hoy', COALESCE((SELECT SUM(monto) FROM pagos WHERE fecha = v_today AND estado = 'confirmado' AND empresa_id = p_empresa_id), 0),
    'cantidad_hoy', (SELECT COUNT(*) FROM pagos WHERE fecha = v_today AND estado = 'confirmado' AND empresa_id = p_empresa_id),
    'total_ayer', COALESCE((SELECT SUM(monto) FROM pagos WHERE fecha = v_yesterday AND estado = 'confirmado' AND empresa_id = p_empresa_id), 0),
    'cantidad_ayer', (SELECT COUNT(*) FROM pagos WHERE fecha = v_yesterday AND estado = 'confirmado' AND empresa_id = p_empresa_id),
    'total_semana', COALESCE((SELECT SUM(monto) FROM pagos WHERE fecha >= v_week_start AND fecha <= v_today AND estado = 'confirmado' AND empresa_id = p_empresa_id), 0),
    'cantidad_semana', (SELECT COUNT(*) FROM pagos WHERE fecha >= v_week_start AND fecha <= v_today AND estado = 'confirmado' AND empresa_id = p_empresa_id),
    'total_semana_anterior', COALESCE((SELECT SUM(monto) FROM pagos WHERE fecha >= v_prev_week_start AND fecha <= v_prev_week_end AND estado = 'confirmado' AND empresa_id = p_empresa_id), 0),
    'cantidad_semana_anterior', (SELECT COUNT(*) FROM pagos WHERE fecha >= v_prev_week_start AND fecha <= v_prev_week_end AND estado = 'confirmado' AND empresa_id = p_empresa_id),
    'total_mes', COALESCE((SELECT SUM(monto) FROM pagos WHERE fecha >= v_month_start AND fecha <= v_month_end AND estado = 'confirmado' AND empresa_id = p_empresa_id), 0),
    'cantidad_mes', (SELECT COUNT(*) FROM pagos WHERE fecha >= v_month_start AND fecha <= v_month_end AND estado = 'confirmado' AND empresa_id = p_empresa_id),
    'promedio_ticket', COALESCE((SELECT AVG(monto) FROM pagos WHERE fecha >= v_month_start AND fecha <= v_month_end AND estado = 'confirmado' AND empresa_id = p_empresa_id), 0),
    'duplicados_hoy', (SELECT COUNT(*) FROM (SELECT banco, referencia FROM pagos WHERE empresa_id = p_empresa_id GROUP BY banco, referencia HAVING COUNT(*) > 1) dup),
    'transacciones_editadas', (SELECT COUNT(*) FROM audit_log WHERE accion = 'editar' AND empresa_id = p_empresa_id AND creado_en >= v_month_start::timestamptz),
    'transacciones_anuladas', (SELECT COUNT(*) FROM pagos WHERE estado = 'anulado' AND empresa_id = p_empresa_id AND actualizado_en >= v_month_start::timestamptz),
    'pendientes_revision', (SELECT COUNT(*) FROM pagos WHERE estado = 'pendiente' AND empresa_id = p_empresa_id),
    'sin_comprobante_total', (SELECT COUNT(*) FROM pagos WHERE empresa_id = p_empresa_id AND (imagen_uri IS NULL OR imagen_uri LIKE 'capacitor://%')),
    'meta_mes', (SELECT meta_ingresos FROM metas_mensuales WHERE mes = v_mes_actual AND empresa_id = p_empresa_id)
  ) INTO result;
  RETURN result;
END;
$function$;
